server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.springcloud.entity.Dept
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
#给微服务取个名
spring:
  application:
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/1214db
    username: root
    password: 981218
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000
#配置将该子项目添加到Eureka子项目的功能
eureka:
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

#给当前服务取个实例别名 instance-id:别名 prefer-ip-address:是否显示IP地址
  instance: 
    instance-id: zbwspringcloud-dept8001
    prefer-ip-address: true

#配置健康状态信息 app.name:软件名称  company.name:公司名称 build.artifactId:项目名称 build.version:项目版本号
info: 
  app.name: zbwspringcloud
  company.name: www.kdc.com
  build.artifactId: springcloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT      
